if [[ $# -eq 0 ]]; then
  echo "hostname must be specified"
  exit 1
fi
echo "setting hostname to $1"
/bin/hostname $1
echo "generating host file"
cat > /etc/hosts <<EOF
# generated by vagrant shell provisioner
10.11.7.201    koala.levelup   koala
10.11.7.202    kangaroo.levelup        kangaroo
10.11.7.203    possum.levelup  possum
10.11.7.204    quoll.levelup   quoll
10.11.7.205    platypus.levelup        platypus
10.11.7.206    echidna.levelup echidna
10.11.7.207    dingo.levelup   dingo
10.11.7.208    wombat.levelup  wombat 
10.11.7.209    wallaby.levelup  wallaby
10.11.7.210    emu.levelup  emu

10.11.7.254    master.levelup  master
EOF
echo "127.0.0.1       $1 $1.levelup    localhost" >> /etc/hosts
echo "setting ip $2"
/sbin/ifconfig eth1 $2

