if [[ $# -eq 0 ]]; then
  echo "hostname must be specified"
  exit 1
fi
echo "setting hostname to $1"
/bin/hostname $1
echo "generating host file"
cat > /etc/hosts <<EOF
# generated by vagrant shell provisioner
192.168.0.201    koala.levelup   koala
192.168.0.202    kangaroo.levelup        kangaroo
192.168.0.203    possum.levelup  possum
192.168.0.204    quoll.levelup   quoll
192.168.0.205    platypus.levelup        platypus
192.168.0.206    echidna.levelup echidna
192.168.0.207    dingo.levelup   dingo

192.168.0.254    master.levelup  master
EOF
echo "127.0.0.1       $1 $1.levelup    localhost" >> /etc/hosts
echo "setting ip $2"
/sbin/ifconfig eth1 $2
#cat > /etc/network/interfaces <<EOF
#auto eth0
#iface eth0 inet dhcp
#
#auto eth1
#iface eth1 inet static 
#    address $2
#    netmask 255.255.255.0
#    post-up route del default dev \$IFACE
#EOF

