if [[ $# -eq 0 ]]; then
  echo "hostname must be specified"
  exit 1
fi
echo "setting hostname to $1"
/bin/hostname $1
echo "generating host file"
cat > /etc/hosts <<EOF
# generated by vagrant shell provisioner
192.168.25.1    koala.levelup   koala
192.168.25.2    kangaroo.levelup        kangaroo
192.168.25.3    possum.levelup  possum
192.168.25.4    quoll.levelup   quoll
192.168.25.5    platypus.levelup        platypus
192.168.25.6    echidna.levelup echidna
192.168.25.7    dingo.levelup   dingo
EOF
echo "127.0.0.1       $1 $1.levelup    localhost" >> /etc/hosts
