  
Vagrant::Config.run do |config|
  config.vm.box = 'debian-606-x64-puppetlabs'
  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/debian-606-x64.box'
  # CentOS takes a while to boot so we need to wait a whole lot longer
  config.ssh.max_tries = 50
  config.ssh.timeout = 300
  config.vm.network :hostonly, "#{ENV['LEVELUP_IP']}" #:bridged, "192.168.0.100"

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  config.vm.share_folder "vagrant-share", "/vagrant/share", "share"
  config.vm.share_folder "git-share", "/vagrant/infrastructure", "../puppet" 
  config.vm.forward_port 80, 9080, :auto => true
  config.vm.forward_port 443, 9443, :auto => true

  config.vm.host_name = "#{ENV['LEVELUP_HOST']}"
  config.vm.customize ['modifyvm', :id, '--memory', '512']
 # config.vm.provision :puppet, :facter => { "fqdn" => "#{ENV['LEVELUP_HOST']}.levelup"} do |puppet|
  #   puppet.manifest_file = 'provision.pp'
  #end

  config.vm.provision :shell do |shell|
    shell.path = "provision.sh"
    shell.args = "#{ENV['LEVELUP_HOST']}"
  end
end
